from __future__ import annotations

import re
from typing import Any

from text_quality import detect_probable_ocr_corruption, find_suspicious_ocr_tokens

MOZI_ALLOWED_TOKENS = {
    "an",
    "ode",
    "confucius",
    "mencius",
    "motse",
    "mozi",
    "yi",
    "yii",
    "ya",
    "yu",
    "tang",
    "wen",
    "wu",
    "tse",
    "hsia",
    "hsii",
    "hsi",
    "huitse",
    "yentse",
    "yiieh",
    "ytieh",
    "yiieb",
    "yiieli",
    "yxieh",
    "kou",
    "lu",
    "kan",
    "mu",
    "kung",
    "meng",
    "shun",
    "yao",
    "chou",
    "chi",
    "chia",
    "chu",
    "hsin",
    "chih",
    "chieh",
    "lii",
    "chuang",
}

MOZI_ALLOWED_HYPHENATED_TOKENS = {
    "all-embracing",
    "all-inclusive",
    "bent-headed",
    "child-bearing",
    "gentle-men",
    "good-looking",
    "high-minded",
    "law-abiding",
    "male-child",
    "sage-king",
    "sage-kings",
    "self-confidence",
    "single-handed",
    "so-called",
    "straight-forwardness",
    "to-day",
    "two-edged",
    "well-being",
    "white-haired",
}

MOZI_SUSPICIOUS_EXACT_TOKENS = {
    "watcliing",
    "sigked",
    "wiiat",
    "wbat",
    "difierent",
    "difierence",
    "oflflcial",
    "quamed",
    "stotiso",
    "v/odiucms",
    "achevemeat",
    "trise",
    "pupu",
    "tee",
    "teeir",
    "teose",
    "teey",
    "teis",
    "teen",
    "inany>",
    "tlie",
    "tliis",
    "tliat",
    "tlien",
    "tlierefore",
    "witli",
    "liave",
    "cliildren",
    "clotking",
    "bundred",
    "afiected",
    "afiection",
    "afiectionate",
    "afectionate",
    "asectionate",
    "atrributed",
    "beginmng",
    "everjhere",
    "efscient",
    "efiective",
    "accoinplish",
    "admdnistration",
    "condenmation",
    "discrinoination",
    "doubtfnl",
    "bimself",
    "pvernors",
    "wisli",
    "mm",
    "wlien",
    "wken",
    "wtiile",
    "wtiy",
    "eiver",
    "eivers",
    "heayen",
    "heawen",
    "eingdom",
    "ofscials",
    "diserent",
    "smau",
    "stiu",
    "wdll",
    "worsliip",
    "ranlc",
    "dranlc",
    "siifiicient",
    "sulbiicient",
    "coibsn",
    "per-inenoy",
    "stabilily",
    "vntuous",
    "tke",
    "tkiis",
    "tkiis.said",
    "l)e",
    "imown",
    "virtne",
    "xmfortnnate",
    "nmnagnanimons",
    "mots",
    "tl",
    "gentlemon",
    "totuons",
    "tttere",
    "djmasties",
    "ghieh",
    "tben",
    "yti",
    "frugahty",
    "tim",
    "djmasty",
    "weavmg",
    "pmods",
    "wonld",
    "bis",
}

MOZI_SUSPICIOUS_HYPHENATED_TOKENS = {
    "acknow-ledge",
    "administra-tion",
    "affec-tionate",
    "agree-ment",
    "amuse-ments",
    "can-not",
    "com-mendation",
    "com-missioned",
    "con-demned",
    "con-tinue",
    "con-scious",
    "de-termining",
    "deprecia-tion",
    "direc-tions",
    "discrimina-tion",
    "doc-trine",
    "en-deavour",
    "every-thing",
    "ex-perienced",
    "exalta-tion",
    "founda-tion",
    "govern-ment",
    "humilia-tion",
    "juris-diction",
    "magnani-mous",
    "punish-ment",
    "punish-ments",
    "respec-tively",
    "termino-logy",
    "there-fore",
    "there-upon",
    "under-stand",
}

MOZI_TOKEN_REPAIRS = {
    "Watcliing": "Watching",
    "sigked": "sighed",
    "Wiiat": "What",
    "wbat": "what",
    "difierent": "different",
    "difierence": "difference",
    "There-fore": "Therefore",
    "There-upon": "Thereupon",
    "oflflcial": "official",
    "quaMed": "qualified",
    "StoTiso": "",
    "v/ODiucms": "Confucius",
    "acHevemeat": "achievement",
    "triSe": "trifle",
    "pupU": "pupil",
    "tEe": "the",
    "tEeir": "their",
    "tEose": "those",
    "tEey": "they",
    "TEey": "They",
    "tEis": "this",
    "tEen": "then",
    "wEo": "who",
    "sEall": "shall",
    "sEould": "should",
    "sEouid": "should",
    "sEoot": "shoot",
    "witE": "with",
    "witFout": "without",
    "tFe": "the",
    "cEariot": "chariot",
    "punisE": "punish",
    "Eonour": "honour",
    "Eave": "have",
    "Eis": "his",
    "faitEful": "faithful",
    "unfaitEful": "unfaithful",
    "wealtEy": "wealthy",
    "inany>": "many",
    "ofScials": "officials",
    "diSerent": "different",
    "tlie": "the",
    "tliis": "this",
    "Tliat": "That",
    "Tlien": "Then",
    "Tlierefore": "Therefore",
    "witli": "with",
    "liave": "have",
    "cliildren": "children",
    "clotking": "clothing",
    "bundred": "hundred",
    "afiected": "affected",
    "afiection": "affection",
    "afiectionate": "affectionate",
    "afectionate": "affectionate",
    "aSectionate": "affectionate",
    "atrributed": "attributed",
    "beginmng": "beginning",
    "caUed": "called",
    "everjhere": "everywhere",
    "efScient": "efficient",
    "efiective": "effective",
    "accoinplish": "accomplish",
    "admdnistration": "administration",
    "condenmation": "condemnation",
    "discrinoination": "discrimination",
    "doubtfnl": "doubtful",
    "bimself": "himself",
    "pvernors": "governors",
    "wisli": "wish",
    "Mm": "him",
    "Wlien": "When",
    "Wken": "When",
    "WTiile": "While",
    "WTiy": "Why",
    "Eiver": "River",
    "Eivers": "Rivers",
    "Heayen": "Heaven",
    "Heawen": "Heaven",
    "Eingdom": "Kingdom",
    "govern-ment": "government",
    "under-stand": "understand",
    "magnani-mous": "magnanimous",
    "exalta-tion": "exaltation",
    "discrimina-tion": "discrimination",
    "respec-tively": "respectively",
    "juris-diction": "jurisdiction",
    "humilia-tion": "humiliation",
    "acknow-ledge": "acknowledge",
    "affec-tionate": "affectionate",
    "com-missioned": "commissioned",
    "com-mendation": "commendation",
    "con-demned": "condemned",
    "con-tinue": "continue",
    "de-termining": "determining",
    "deprecia-tion": "depreciation",
    "en-deavour": "endeavour",
    "ex-perienced": "experienced",
    "founda-tion": "foundation",
    "agree-ment": "agreement",
    "direc-tions": "directions",
    "doc-trine": "doctrine",
    "every-thing": "everything",
    "termino-logy": "terminology",
    "punish-ment": "punishment",
    "punish-ments": "punishments",
    "administra-tion": "administration",
    "amuse-ments": "amusements",
    "con-scious": "conscious",
    "can-not": "cannot",
    "rebeUious": "rebellious",
    "FuTse": "Fu Tse",
    "there-upon": "thereupon",
    "tEem": "them",
    "whoeTeir": "whoever",
    "universaMove": "universal love",
    "inniimeraMe": "innumerable",
    "inmimerable": "innumerable",
    "ChuYung": "Chu Yung",
    "jErom": "from",
    "dranlc": "drank",
    "sulBiicient": "sufficient",
    "siifiicient": "sufficient",
    "stiU": "still",
    "wlien": "when",
    "wdll": "will",
    "ranlc": "rank",
    "smaU": "small",
    "tliat": "that",
    "oSering": "offering",
    "wMch": "which",
    "foUowmg": "following",
    "universaUy": "universally",
    "unaSectionate": "unaffectionate",
    "lTiat": "that",
    "jSire": "fire",
    "tMeves": "thieves",
    "tLe": "the",
    "YiLi": "Yi Li",
    "indireGtly": "indirectly",
    "woMd": "world",
    "iTiao": "Miao",
    "coiBSn": "coffin",
    "per-inenoy": "permanency",
    "stabilily": "stability",
    "vntuous": "virtuous",
    "tke": "the",
    "Tkiis": "Thus",
    "Tkiis.said": "Thus said",
    "l)e": "be",
    "Imown": "known",
    "virtne": "virtue",
    "xmfortnnate": "unfortunate",
    "nmnagnanimons": "unmagnanimous",
    "Tvere": "were",
    "pufi": "puff",
    "ofi": "off",
    "VTio": "Who",
    "iimocent": "innocent",
    "tradictory": "contrary",
    "wih": "will",
    "tonse": "house",
    "Tvere": "were",
    "Hs": "his",
    "virtne,": "virtue,",
    "Mots": "Motse",
    "Mots©": "Motse",
    "TL": "The",
    "TL.©": "The",
    "gentlemon": "gentlemen",
    "on©": "one",
    "sage-Mngs": "sage-kings",
    "Wn": "Wu",
    "Prom": "From",
    "TOtuons": "multitudes",
    "tttere": "there",
    "Djmasties": "Dynasties",
    "Ghieh": "Chieh",
    "Tben": "Then",
    "Yti": "Yu",
    "frugahty": "frugality",
    "tim": "him",
    "djmasty": "dynasty",
    "tli©": "the",
    "weavmg": "weaving",
    "pmods": "periods",
    "wonld": "would",
    "bis": "his",
    "bo": "be",
    "ttere": "there",
    "benefi.cial": "beneficial",
    "worsliip": "worship",
    "oSer": "offer",
    "Djhasties": "Dynasties",
    "wffien": "when",
    "Tbe": "The",
    "tlieni-selves": "themselves",
    "tbeir": "their",
    "ISrow": "Now",
    "ofier": "offer",
    "insufiS.cient": "insufficient",
    "w-ant": "want",
    "imiversalize": "universalize",
    "institn": "institute",
    "compostion": "composition",
    "amshed": "banished",
    "bigb": "high",
    "execu-tion": "execution",
    "rardc": "rank",
    "goyernment": "government",
    "emplo3dng": "employing",
    "governinent": "government",
    "pnnislied": "punished",
    "witL": "with",
    "enliglitemnent": "enlightenment",
    "consolate": "console",
    "oj0S.cers": "officers",
    "Oonfucianist": "Confucianist",
    "ghing": "Ching",
    "barm": "harm",
    "tbe": "the",
    "Mots0": "Motse",
    "Yi.2": "Yi.",
    "tliore": "there",
    "suffi.cient": "sufficient",
    "otliers": "others",
    "Tlieieupoii": "Thereupon",
    "wliat": "what",
    "an3rwhere": "anywhere",
    "sa3drLg": "saying",
    "unxighteousness": "unrighteousness",
    "ttis": "this",
    "wliy": "why",
    "yoxmger": "younger",
    "oj0S.cials": "officials",
    "an3d3hing": "anything",
    "ofiering": "offering",
    "tbey": "they",
    "tile": "the",
    "taldng": "taking",
    "conimon": "common",
    "pxmish": "punish",
    "Emowing": "Knowing",
    "tli©": "the",
    "graded.2": "graded.",
    "Ofiensive": "Offensive",
    "tb©": "the",
}

MOZI_TOKEN_REPAIRS_CASEFOLDED = {token.casefold(): replacement for token, replacement in MOZI_TOKEN_REPAIRS.items()}
MOZI_LITERAL_REPAIRS = {
    "tli©": "the",
    "tb©": "the",
}

MOZI_PHRASE_REPAIRS: list[dict[str, Any]] = [
    {
        "pattern": re.compile(
            r"Motse said : All tEe riders in tEe world desire tEeir states to be wealtEy, tEeir people to be inany> and tEeir government and jurisdiction to be orderly\."
        ),
        "replacement": "Motse said : All the rulers in the world desire their states to be wealthy, their people to be many, and their government and jurisdiction to be orderly.",
        "correction_type": "curated_phrase_repair",
        "confidence": 0.99,
        "mode": "curated",
        "section_ids": {"mozi-010-exaltation-of-the-virtuous-iii"},
    },
    {
        "pattern": re.compile(
            r"Who can handle virtue even at such an early time as that of Confucius The to sFow Fow in tFo: past tFe rulers could not do witFout befriending subordinates and helpers\."
        ),
        "replacement": "Who can handle virtue even at such an early time as that of Confucius? This goes to show how in the past the rulers could not do without befriending subordinates and helpers.",
        "correction_type": "curated_phrase_repair",
        "confidence": 0.99,
        "mode": "curated",
        "section_ids": {"mozi-009-exaltation-of-the-virtuous-ii"},
    },
    {
        "pattern": re.compile(r"StoTiso,\s+An Ode says\s*:"),
        "replacement": "An Ode says :",
        "correction_type": "note_residue_repair",
        "confidence": 0.96,
        "mode": "automatic",
        "section_ids": {"mozi-003-that-which-is-affectable"},
    },
    {
        "pattern": re.compile(r'^"\s*Tu Kan Mu was a pupU of Tse Hsia, who was a noted disciple of v/ODiucms\s*$', re.IGNORECASE),
        "replacement": "",
        "correction_type": "note_residue_removal",
        "confidence": 0.99,
        "mode": "automatic",
        "section_ids": {"mozi-003-that-which-is-affectable"},
    },
    {
        "pattern": re.compile(r"pages to refer to this work\.", re.IGNORECASE),
        "replacement": "",
        "correction_type": "note_residue_removal",
        "confidence": 0.99,
        "mode": "automatic",
        "section_ids": {"mozi-008-exaltation-of-the-virtuous-i"},
    },
    {
        "pattern": re.compile(r"\s*Tse Lu is another of the seventy-two best disciples of Confucius\.\s*$"),
        "replacement": "",
        "correction_type": "note_residue_removal",
        "confidence": 0.99,
        "mode": "automatic",
        "section_ids": {"mozi-038-esteem-for-righteousness"},
    },
    {
        "pattern": re.compile(r"Tse Lu were exhausted, and his followers became so ill that they were unable to rise/'\s*’"),
        "replacement": "Tse Lu was exhausted, and his followers became so ill that they were unable to rise.",
        "correction_type": "curated_phrase_repair",
        "confidence": 0.97,
        "mode": "curated",
        "section_ids": {"mozi-038-esteem-for-righteousness"},
    },
    {
        "pattern": re.compile(r"^ow,\s+what does Heaven desire", re.IGNORECASE),
        "replacement": "Now, what does Heaven desire",
        "correction_type": "automatic_phrase_repair",
        "confidence": 0.92,
        "mode": "automatic",
        "section_ids": None,
    },
    {
        "pattern": re.compile(r"^Motse,\s+the\s+Neglected\s+Rival\s+of\s+Confucius,\s+chap\.\s+i\.\s*$", re.IGNORECASE),
        "replacement": "",
        "correction_type": "note_residue_removal",
        "confidence": 0.99,
        "mode": "curated",
        "section_ids": {"mozi-005-the-seven-worries"},
    },
    {
        "pattern": re.compile(r"\?\s+desires righteousness", re.IGNORECASE),
        "replacement": "? It desires righteousness",
        "correction_type": "automatic_phrase_repair",
        "confidence": 0.92,
        "mode": "automatic",
        "section_ids": None,
    },
    {
        "pattern": re.compile(r"\bMots©\b"),
        "replacement": "Motse",
        "correction_type": "automatic_phrase_repair",
        "confidence": 0.95,
        "mode": "automatic",
        "section_ids": None,
    },
    {
        "pattern": re.compile(r"\bTL\.©\b"),
        "replacement": "The",
        "correction_type": "automatic_phrase_repair",
        "confidence": 0.95,
        "mode": "automatic",
        "section_ids": None,
    },
    {
        "pattern": re.compile(r"\bon©\b"),
        "replacement": "one",
        "correction_type": "automatic_phrase_repair",
        "confidence": 0.95,
        "mode": "automatic",
        "section_ids": None,
    },
    {
        "pattern": re.compile(r"\btli©\b"),
        "replacement": "the",
        "correction_type": "automatic_phrase_repair",
        "confidence": 0.95,
        "mode": "automatic",
        "section_ids": None,
    },
    {
        "pattern": re.compile(
            r'On the other hand, it desires people having energy to work for each other, those knowing the way to teach each other, These are the two opening lines of the ode " Hsiao Ming " in Shih Ching\.',
            re.IGNORECASE,
        ),
        "replacement": "On the other hand, it desires people having energy to work for each other, those knowing the way to teach each other, and those possessing wealth to share with each other.",
        "correction_type": "curated_phrase_repair",
        "confidence": 0.98,
        "mode": "curated",
        "section_ids": {"mozi-026-condemnation-of-music-i"},
    },
    {
        "pattern": re.compile(
            r"^On the other hand, it desires people having energy to work for each other, those knowing the way to teach each other,.*$",
            re.IGNORECASE,
        ),
        "replacement": "On the other hand, it desires people having energy to work for each other, those knowing the way to teach each other, and those possessing wealth to share with each other.",
        "correction_type": "curated_phrase_repair",
        "confidence": 0.98,
        "mode": "curated",
        "section_ids": {"mozi-026-condemnation-of-music-i"},
    },
    {
        "pattern": re.compile(r"^Legge,\s+vol\.\s+iv,\s+p\.\s*$", re.IGNORECASE),
        "replacement": "",
        "correction_type": "note_residue_removal",
        "confidence": 0.99,
        "mode": "automatic",
        "section_ids": {"mozi-026-condemnation-of-music-i"},
    },
    {
        "pattern": re.compile(r"^363,\s+renders it thus:\s+—\s+and those possessing wealth to share with each other\.\s*$", re.IGNORECASE),
        "replacement": "",
        "correction_type": "note_residue_removal",
        "confidence": 0.99,
        "mode": "automatic",
        "section_ids": {"mozi-026-condemnation-of-music-i"},
    },
    {
        "pattern": re.compile(r"^363,\s+renders it thus:.*$", re.IGNORECASE),
        "replacement": "",
        "correction_type": "note_residue_removal",
        "confidence": 0.99,
        "mode": "automatic",
        "section_ids": {"mozi-026-condemnation-of-music-i"},
    },
    {
        "pattern": re.compile(r"^363,\s+renders it thus\s*:.*$", re.IGNORECASE),
        "replacement": "",
        "correction_type": "note_residue_removal",
        "confidence": 0.99,
        "mode": "automatic",
        "section_ids": {"mozi-026-condemnation-of-music-i"},
    },
    {
        "pattern": re.compile(
            r"^Who are those that love a Compare this them. of Motse.?s with the foUowmg from Seneca, On Benefits, iv, 6:.*$",
            re.IGNORECASE,
        ),
        "replacement": "Who are those that love the people and benefit the people, obey the will of Heaven and obtain reward from Heaven?",
        "correction_type": "curated_phrase_repair",
        "confidence": 0.97,
        "mode": "curated",
        "section_ids": {"mozi-026-condemnation-of-music-i"},
    },
    {
        "pattern": re.compile(r"^Who are those that love a .*On Benefits, iv, 6:.*$", re.IGNORECASE),
        "replacement": "Who are those that love the people and benefit the people, obey the will of Heaven and obtain reward from Heaven?",
        "correction_type": "curated_phrase_repair",
        "confidence": 0.97,
        "mode": "curated",
        "section_ids": {"mozi-026-condemnation-of-music-i"},
    },
    {
        "pattern": re.compile(r"^Who are those that love a .*On Benefits,\s*iv,\s*6\s*:.*$", re.IGNORECASE),
        "replacement": "Who are those that love the people and benefit the people, obey the will of Heaven and obtain reward from Heaven?",
        "correction_type": "curated_phrase_repair",
        "confidence": 0.97,
        "mode": "curated",
        "section_ids": {"mozi-026-condemnation-of-music-i"},
    },
    {
        "pattern": re.compile(r"^If a man bestows upon us a house that is delicately beautified with painting, statues, gildings, and marbles,.*$", re.IGNORECASE),
        "replacement": "",
        "correction_type": "note_residue_removal",
        "confidence": 0.99,
        "mode": "automatic",
        "section_ids": {"mozi-026-condemnation-of-music-i"},
    },
    {
        "pattern": re.compile(r"^And is it nothing now to sleep under the canopy of heaven,.*$", re.IGNORECASE),
        "replacement": "",
        "correction_type": "note_residue_removal",
        "confidence": 0.99,
        "mode": "automatic",
        "section_ids": {"mozi-026-condemnation-of-music-i"},
    },
    {
        "pattern": re.compile(r"^Besides this, some of its early kings\.\s*$", re.IGNORECASE),
        "replacement": "Besides this, it is also recorded on the bamboos and silk, cut in the metals and stones, and engraved on the plates and cups to be handed down to posterity.",
        "correction_type": "curated_phrase_repair",
        "confidence": 0.97,
        "mode": "curated",
        "section_ids": {"mozi-026-condemnation-of-music-i"},
    },
    {
        "pattern": re.compile(r"^According to Legge,\s+vol\.\s+iv,\s+p\.\s*$", re.IGNORECASE),
        "replacement": "",
        "correction_type": "note_residue_removal",
        "confidence": 0.99,
        "mode": "automatic",
        "section_ids": {"mozi-026-condemnation-of-music-i"},
    },
    {
        "pattern": re.compile(r"^464,\s+the stanza reads:.*it is also recorded on\.\s*$", re.IGNORECASE),
        "replacement": "",
        "correction_type": "note_residue_removal",
        "confidence": 0.99,
        "mode": "automatic",
        "section_ids": {"mozi-026-condemnation-of-music-i"},
    },
    {
        "pattern": re.compile(r"^the bamboos and silk, cut in the metals and stones, and engraved on the plates and cups to be handed down to posterity\.\s*$", re.IGNORECASE),
        "replacement": "",
        "correction_type": "note_residue_removal",
        "confidence": 0.98,
        "mode": "automatic",
        "section_ids": {"mozi-026-condemnation-of-music-i"},
    },
    {
        "pattern": re.compile(r"^Therefore those who practise i' magnanimity and righteousness must examine it and V vigorously refute it\.\s*$", re.IGNORECASE),
        "replacement": "Therefore those who practise magnanimity and righteousness must examine it and vigorously refute it.",
        "correction_type": "curated_phrase_repair",
        "confidence": 0.97,
        "mode": "curated",
        "section_ids": {"mozi-036-minor-illustrations"},
    },
    {
        "pattern": re.compile(r"^, '.V'/S\.l'\.\s*$", re.IGNORECASE),
        "replacement": "",
        "correction_type": "note_residue_removal",
        "confidence": 0.99,
        "mode": "automatic",
        "section_ids": {"mozi-036-minor-illustrations"},
    },
    {
        "pattern": re.compile(r"^.*V'/S.*$", re.IGNORECASE),
        "replacement": "",
        "correction_type": "note_residue_removal",
        "confidence": 0.99,
        "mode": "automatic",
        "section_ids": {"mozi-036-minor-illustrations"},
    },
    {
        "pattern": re.compile(
            r"^\[ The Confucianist says: Love among relations should depend upon the degree of relationship, and honour to the virtuous should be graded\.2 This is to advocate a discrimination among the near and the distant relations and among the respectable and the humble\.\s*$",
            re.IGNORECASE,
        ),
        "replacement": "The Confucianists say that love among relations should depend on the degree of relationship, and honour to the virtuous should be graded. This advocates discrimination among near and distant relations and among the respectable and the humble.",
        "correction_type": "curated_phrase_repair",
        "confidence": 0.95,
        "mode": "curated",
        "section_ids": {"mozi-036-minor-illustrations"},
    },
    {
        "pattern": re.compile(r"^When his parent dies he first lets him lie there without vol\. i, p\.\s*$", re.IGNORECASE),
        "replacement": "",
        "correction_type": "note_residue_removal",
        "confidence": 0.99,
        "mode": "automatic",
        "section_ids": {"mozi-036-minor-illustrations"},
    },
    {
        "pattern": re.compile(r"^270: \" The decreasing measures of the love due to relatives and the steps in the honour due to the worthy, are produced by the principle of propriety\.’ r\s*$", re.IGNORECASE),
        "replacement": "",
        "correction_type": "note_residue_removal",
        "confidence": 0.99,
        "mode": "automatic",
        "section_ids": {"mozi-036-minor-illustrations"},
    },
    {
        "pattern": re.compile(r"^As to the result of the application of the i doctrine of fatalism to the government of the empire, to \| worship Heaven and the spirits above with it Heaven and the spirits will not be pleased, and to nurture the people below with it they will not be benefited but will be demoralized and \| cannot be employed\.\s*$", re.IGNORECASE),
        "replacement": "As to the result of applying the doctrine of fatalism to the government of the empire, Heaven and the spirits above will not be pleased, and the people below will not be benefited but demoralized and unemployable.",
        "correction_type": "curated_phrase_repair",
        "confidence": 0.95,
        "mode": "curated",
        "section_ids": {"mozi-036-minor-illustrations"},
    },
    {
        "pattern": re.compile(r"^\| Therefore Motse said: If the gentlemen of the world really desire to procure benefits for the world and destroy its calamities they cannot but vigorously refute the doctrine ij of fatalism\.\s*$", re.IGNORECASE),
        "replacement": "Therefore Motse said: If the gentlemen of the world really desire to procure benefits for the world and destroy its calamities, they must vigorously refute the doctrine of fatalism.",
        "correction_type": "curated_phrase_repair",
        "confidence": 0.97,
        "mode": "curated",
        "section_ids": {"mozi-036-minor-illustrations"},
    },
]

MOZI_HEADING_RESIDUE_RE = re.compile(
    r"(?:the works of motse|the w[oq]rks of motse|self-cultivation\s*\([ivx]+\)|the seven causes of anxiety|identification with the superior\s*\([ivx]+\)|will of heaven\s*\([ivx]+\)|condemnation of music\s*\([ivx]+\)|anti-confucianism\s*\([ivx]+\)|simplicity in funerals?\s*\([ivx]+\))",
    re.IGNORECASE,
)

MOZI_NOTE_RESIDUE_MARKERS = (
    "Legge, vol.",
    "According to Legge",
    "Compare this them",
    "Compare this theme",
    "On Benefits, iv, 6",
    "These are the two opening lines of the ode",
    "renders it thus",
    "vol. i, p.",
)

TOKEN_RE = re.compile(r"\b[A-Za-z][A-Za-z0-9'/<>\-:.’]*[A-Za-z0-9]\b")


def _apply_case(template: str, replacement: str) -> str:
    if not replacement:
        return replacement
    if template.isupper():
        return replacement.upper()
    if template.istitle():
        return replacement.capitalize()
    return replacement


def detect_mozi_ocr_issues(text: str) -> list[dict[str, str]]:
    issues = find_suspicious_ocr_tokens(
        text,
        allowed_tokens=MOZI_ALLOWED_TOKENS | MOZI_ALLOWED_HYPHENATED_TOKENS,
        suspicious_exact_tokens=MOZI_SUSPICIOUS_EXACT_TOKENS,
        suspicious_hyphenated_tokens=MOZI_SUSPICIOUS_HYPHENATED_TOKENS,
    )
    lowered = " ".join(text.casefold().split())
    if MOZI_HEADING_RESIDUE_RE.search(lowered):
        issues.append({"token": text[:80], "issue_type": "heading_residue"})
    if any(marker.casefold() in lowered for marker in MOZI_NOTE_RESIDUE_MARKERS):
        issues.append({"token": text[:80], "issue_type": "note_residue"})
    if detect_probable_ocr_corruption(
        text,
        allowed_tokens=MOZI_ALLOWED_TOKENS | MOZI_ALLOWED_HYPHENATED_TOKENS,
        suspicious_exact_tokens=MOZI_SUSPICIOUS_EXACT_TOKENS,
        suspicious_hyphenated_tokens=MOZI_SUSPICIOUS_HYPHENATED_TOKENS,
    ):
        return issues
    return issues


def repair_mozi_ocr_text(
    text: str,
    *,
    section_id: str,
    source_path: str,
) -> tuple[str, list[dict[str, Any]], list[dict[str, str]], list[dict[str, str]]]:
    def apply_phrase_repairs(value: str) -> str:
        cleaned_value = value
        for repair in MOZI_PHRASE_REPAIRS:
            section_ids = repair["section_ids"]
            if section_ids is not None and section_id not in section_ids:
                continue
            while True:
                match = repair["pattern"].search(cleaned_value)
                if match is None:
                    break
                raw_value = match.group(0)
                updated_value = f"{cleaned_value[:match.start()]}{repair['replacement']}{cleaned_value[match.end():]}"
                if updated_value == cleaned_value:
                    break
                cleaned_value = updated_value
                repairs.append(
                    {
                        "section_id": section_id,
                        "raw_token": raw_value,
                        "corrected_token": repair["replacement"],
                        "correction_type": repair["correction_type"],
                        "confidence": repair["confidence"],
                        "mode": repair["mode"],
                        "source_path": source_path,
                    }
                )
        return cleaned_value

    pre_issues = detect_mozi_ocr_issues(text)
    repairs: list[dict[str, Any]] = []
    cleaned = text
    for raw_value, replacement in MOZI_LITERAL_REPAIRS.items():
        if raw_value not in cleaned:
            continue
        cleaned = cleaned.replace(raw_value, replacement)
        repairs.append(
            {
                "section_id": section_id,
                "raw_token": raw_value,
                "corrected_token": replacement,
                "correction_type": "automatic_literal_repair",
                "confidence": 0.95,
                "mode": "automatic",
                "source_path": source_path,
            }
        )
    cleaned = apply_phrase_repairs(cleaned)

    token_repairs = MOZI_TOKEN_REPAIRS
    rebuilt: list[str] = []
    cursor = 0
    for match in TOKEN_RE.finditer(cleaned):
        rebuilt.append(cleaned[cursor:match.start()])
        token = match.group(0)
        replacement = token_repairs.get(token)
        if replacement is None:
            replacement = MOZI_TOKEN_REPAIRS_CASEFOLDED.get(token.casefold())
            if replacement is not None:
                replacement = _apply_case(token, replacement)
        if replacement is None:
            rebuilt.append(token)
        else:
            rebuilt.append(replacement)
            repairs.append(
                {
                    "section_id": section_id,
                    "raw_token": token,
                    "corrected_token": replacement,
                    "correction_type": "automatic_token_repair",
                    "confidence": 0.95,
                    "mode": "automatic",
                    "source_path": source_path,
                }
            )
        cursor = match.end()
    rebuilt.append(cleaned[cursor:])
    cleaned = "".join(rebuilt)
    cleaned = apply_phrase_repairs(cleaned)
    cleaned = re.sub(r"\s+", " ", cleaned).strip(" ;")
    cleaned = cleaned.replace("''", '"').replace("’’", '"').replace("“", '"').replace("”", '"')
    cleaned = re.sub(r'\s+([,.;:?!])', r"\1", cleaned)

    remaining_issues = detect_mozi_ocr_issues(cleaned)
    return cleaned, repairs, pre_issues, remaining_issues
